# Generated by Django 6.0.7 on 2026-08-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_review_author_delete_author_review_author'),
        ('users', '0003_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fan',
            field=models.ManyToManyField(blank=True, to='main.game'),
        ),
    ]
